<a href="https://colab.research.google.com/github/Jwainlee/python-baby/blob/main/CNN_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>CNN(Convolution Neural Network)

**Convolution Layer**

Conv1D, Conv2D, Conv3D, SeparableConv1D, SeparableConv2D, DepthwiseConv2D, Conv2DTranspose, Conv3DTransopse

In [2]:
import tensorflow as tf
from tensorflow import keras

In [4]:
shape = (4, 28, 28, 3)
x = tf.random.normal(shape)
y = tf.keras.layers.Conv2D(2, 3, activation = 'relu', input_shape = shape[1:])(x)
print(y.shape)

(4, 26, 26, 2)


In [7]:
shape[1:]

(28, 28, 3)

**Pooling Layer**

MaxPooling1D, MaxPooling2D, AveragePooling1D, AveragePooling2D, GlobalMaxPooling1D, GlobalMaxPooling2D, GlobalAveragePooling1D, GlobalAveragePooling2D

In [21]:
x = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x.shape)
x = tf.reshape(x, [1, 3, 3, 1])
print(x)
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size = (2, 2), strides = (1, 1), padding = 'valid')
print(max_pool_2d(x))

(3, 3)
tf.Tensor(
[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]

  [[7]
   [8]
   [9]]]], shape=(1, 3, 3, 1), dtype=int32)
tf.Tensor(
[[[[5]
   [6]]

  [[8]
   [9]]]], shape=(1, 2, 2, 1), dtype=int32)
